#!/bin/bash
# PR 자동 생성 유틸리티
# 사용: ./create-pr.sh <branch-name> <title> [description]
# 예: ./create-pr.sh component/button "[designer] 박나현: Button 컴포넌트" "..."

set -euo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-.}"
cd "$PROJECT_DIR"

# ──────────────────────────────────────
# 인자 검증
# ──────────────────────────────────────
if [ $# -lt 2 ]; then
    echo "❌ 사용법: ./create-pr.sh <branch> <title> [description]"
    exit 1
fi

BRANCH_NAME="$1"
PR_TITLE="$2"
PR_BODY="${3:-}"

# ──────────────────────────────────────
# GH 토큰 확인
# ──────────────────────────────────────
if [ -z "${GH_TOKEN:-}" ]; then
    if [ -f ".gh-token" ]; then
        export GH_TOKEN=$(cat .gh-token | tr -d '[:space:]')
    else
        echo "❌ GitHub 토큰을 찾을 수 없습니다. .gh-token 파일을 확인하세요."
        exit 1
    fi
fi

# ──────────────────────────────────────
# 브랜치 확인
# ──────────────────────────────────────
CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || echo "")
if [ "$CURRENT_BRANCH" != "$BRANCH_NAME" ]; then
    echo "⚠️  현재 브랜치: $CURRENT_BRANCH"
    echo "   PR 생성 브랜치: $BRANCH_NAME"
    echo ""
    echo "브랜치를 전환하시겠습니까? (y/n)"
    read -r CONFIRM
    if [ "$CONFIRM" != "y" ]; then
        echo "취소되었습니다."
        exit 1
    fi
    git checkout "$BRANCH_NAME" || {
        echo "❌ 브랜치 전환 실패"
        exit 1
    }
fi

# ──────────────────────────────────────
# PR 본문 생성 (PR_BODY가 없는 경우)
# ──────────────────────────────────────
if [ -z "$PR_BODY" ]; then
    # .claude/templates/pr-template.md 참고
    PR_BODY="$(cat <<EOF
## 변경 사항

- 변경 내용 1
- 변경 내용 2

## 테스트

- [ ] 모든 테스트 통과
- [ ] Storybook에서 렌더링 확인

## 체크리스트

- [ ] 코드 리뷰 준비 완료
- [ ] 문서 업데이트 완료
- [ ] 관련 이슈 링크됨

---
Generated by Claude Code
EOF
)"
fi

# ──────────────────────────────────────
# git push
# ──────────────────────────────────────
echo "📤 브랜치 푸시 중..."
if ! git push -u origin "$BRANCH_NAME"; then
    echo "⚠️  브랜치가 이미 업스트림에 있거나 푸시 실패"
fi

# ──────────────────────────────────────
# PR 생성 (curl 기반 - .gh-token만 사용)
# ──────────────────────────────────────
echo "📝 PR 생성 중..."

# GitHub API 정보 추출
REPO_URL=$(git remote get-url origin)
REPO=$(echo "$REPO_URL" | sed 's|.*github.com[:/]||' | sed 's|\.git$||')
IFS='/' read -r OWNER REPO_NAME <<< "$REPO"

# API 요청 데이터
PR_DATA=$(cat <<EOF
{
  "title": "$PR_TITLE",
  "body": "$PR_BODY",
  "head": "$BRANCH_NAME",
  "base": "main"
}
EOF
)

# PR 생성 API 호출 (curl로 .gh-token 사용)
PR_RESPONSE=$(curl -s -X POST \
  -H "Authorization: token $GH_TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Content-Type: application/json" \
  -d "$PR_DATA" \
  "https://api.github.com/repos/$OWNER/$REPO_NAME/pulls" 2>/dev/null)

# PR 생성 결과 확인
PR_NUMBER=$(echo "$PR_RESPONSE" | grep -o '"number": [0-9]*' | grep -o '[0-9]*' | head -1)
PR_ERROR=$(echo "$PR_RESPONSE" | grep -o '"message": "[^"]*' | head -1)

if [ -n "$PR_NUMBER" ]; then
    echo ""
    echo "✅ PR 생성 완료!"
    echo "📍 PR URL: https://github.com/$OWNER/$REPO_NAME/pull/$PR_NUMBER"
else
    echo "❌ PR 생성 실패"
    if [ -n "$PR_ERROR" ]; then
        echo "오류: $PR_ERROR"
    fi
    exit 1
fi

# ──────────────────────────────────────
# 상태 기록
# ──────────────────────────────────────
if [ -n "$PR_NUMBER" ]; then
    TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
    PR_LOG=".claude/state/logs/pr-history.log"
    echo "[$TIMESTAMP] PR#$PR_NUMBER created: $PR_TITLE" >> "$PR_LOG" 2>/dev/null || true
fi
