#!/bin/bash
# PR 자동 생성 유틸리티
# 사용: ./create-pr.sh <branch-name> <title> [description]
# 예: ./create-pr.sh component/button "[designer] 박나현: Button 컴포넌트" "..."

set -euo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-.}"
cd "$PROJECT_DIR"

# ──────────────────────────────────────
# 인자 검증
# ──────────────────────────────────────
if [ $# -lt 2 ]; then
    echo "❌ 사용법: ./create-pr.sh <branch> <title> [description]"
    exit 1
fi

BRANCH_NAME="$1"
PR_TITLE="$2"
PR_BODY="${3:-}"

# ──────────────────────────────────────
# GH 토큰 확인
# ──────────────────────────────────────
if [ -z "${GH_TOKEN:-}" ]; then
    if [ -f ".gh-token" ]; then
        export GH_TOKEN=$(cat .gh-token | tr -d '[:space:]')
    else
        echo "❌ GitHub 토큰을 찾을 수 없습니다. .gh-token 파일을 확인하세요."
        exit 1
    fi
fi

# ──────────────────────────────────────
# 브랜치 확인
# ──────────────────────────────────────
CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || echo "")
if [ "$CURRENT_BRANCH" != "$BRANCH_NAME" ]; then
    echo "⚠️  현재 브랜치: $CURRENT_BRANCH"
    echo "   PR 생성 브랜치: $BRANCH_NAME"
    echo ""
    echo "브랜치를 전환하시겠습니까? (y/n)"
    read -r CONFIRM
    if [ "$CONFIRM" != "y" ]; then
        echo "취소되었습니다."
        exit 1
    fi
    git checkout "$BRANCH_NAME" || {
        echo "❌ 브랜치 전환 실패"
        exit 1
    }
fi

# ──────────────────────────────────────
# PR 본문 생성 (PR_BODY가 없는 경우)
# ──────────────────────────────────────
if [ -z "$PR_BODY" ]; then
    # .claude/templates/pr-template.md 참고
    PR_BODY="$(cat <<EOF
## 변경 사항

- 변경 내용 1
- 변경 내용 2

## 테스트

- [ ] 모든 테스트 통과
- [ ] Storybook에서 렌더링 확인

## 체크리스트

- [ ] 코드 리뷰 준비 완료
- [ ] 문서 업데이트 완료
- [ ] 관련 이슈 링크됨

---
Generated by Claude Code
EOF
)"
fi

# ──────────────────────────────────────
# git push
# ──────────────────────────────────────
echo "📤 브랜치 푸시 중..."
if ! git push -u origin "$BRANCH_NAME"; then
    echo "⚠️  브랜치가 이미 업스트림에 있거나 푸시 실패"
fi

# ──────────────────────────────────────
# PR 생성
# ──────────────────────────────────────
echo "📝 PR 생성 중..."
if gh pr create \
    --title "$PR_TITLE" \
    --body "$PR_BODY" \
    --base main \
    --head "$BRANCH_NAME"; then

    echo ""
    echo "✅ PR 생성 완료!"

    # PR 링크 출력
    PR_NUMBER=$(gh pr list --head "$BRANCH_NAME" --json number --jq '.[0].number' 2>/dev/null || echo "")
    if [ -n "$PR_NUMBER" ]; then
        REPO=$(git remote get-url origin | sed 's|.*github.com/||' | sed 's|\.git$||')
        echo "📍 PR URL: https://github.com/$REPO/pull/$PR_NUMBER"

        # PR 상태 표시
        echo ""
        echo "📊 PR 상태:"
        gh pr view "$PR_NUMBER" --json statusCheckRollup,reviewDecision,isDraft --jq '.statusCheckRollup, .reviewDecision, .isDraft'
    fi
else
    echo "❌ PR 생성 실패"
    exit 1
fi

# ──────────────────────────────────────
# 상태 기록
# ──────────────────────────────────────
if [ -n "$PR_NUMBER" ]; then
    TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
    PR_LOG=".claude/state/logs/pr-history.log"
    echo "[$TIMESTAMP] PR#$PR_NUMBER created: $PR_TITLE" >> "$PR_LOG" 2>/dev/null || true
fi
